export const PATH_COLOR = "#ff2a52";
export const STAR_BTNS = [
  "FLAME_START",
  "FLAME_START_2",
  "MIST_START",
  "GALAXY_START",
  "FEAR_START",
  "ABYSS_START",
  "FOOL_START",
  "MIDNIGHT_START",
  "WAR_START",
  "SHIELD_START",
  "DARKNESS_START",
  "CASTLE_START",
  "STARS_START",
  "EXILE_START",
  "FINALITY_START",
  "CHARIOT_START",
];
export const INFINITY_PATHS = [
  "AVX_PATH_236",
  "AVX_PATH_237",
  "AVX_PATH_238",
  "AVX_PATH_239",
  "AVX_PATH_240",
  "AVX_PATH_241",
];
export const COLLECTOR_BTNS = [
  "GALAXY_SPECIAL_11",
  "GALAXY_SPECIAL_12",
  "GALAXY_SPECIAL_13",
  "GALAXY_SPECIAL_14",
  "GALAXY_SPECIAL_15",
];
export const COLLECTOR_COSTS = [0, 1, 1, 2, 3];
export const REMOVE_BTNS = [
  "AVX_SPECIAL_241",
  "AVX_SPECIAL_242",
  "MIDNIGHT_SPECIAL_19",
  "MIDNIGHT_SPECIAL_20",
  "MIDNIGHT_SPECIAL_21",
];
export const BOLT_GATES = [
  "MIST_GATE_7",
  "MIST_GATE_8",
  "MIST_GATE_23",
  "MIST_GATE_24",
  "MIST_GATE_25",
  "MIST_GATE_26",
  "MIST_GATE_27",
  "MIST_GATE_28",
  "MIST_GATE_29",
];
export const ANIM_TIME = 200;
export const MAX_ROSTER = 4;
export const INFINITY_COORDINATES = [
  { x: 3953, y: 5924 },
  { x: 3964, y: 5771 },
  { x: 4058, y: 5648 },
  { x: 4222, y: 5599 },
  { x: 4395, y: 5648 },
  { x: 4492, y: 5772 },
];

// Special Paths
export const MKRAAN_GATE_PATH = "AVX_PATH_216";
export const PHOENIX_FIVE_PATH = "AVX_PATH_217";
export const INFINITY_GAUNTLET_ROAD_PATH = "AVX_PATH_235";
export const FIRST_BROOD_QUEEN = "AVX_BROOD_QUEEN_144";
// SPECIAL BUTTONS
export const DARK_PHOENIX_BTN = "AVX_DARK_PHOENIX_229";
export const PHOENIX_FIVE_BTNS = [
  "AVX_MAGIK_PHOENIX_FIVE_224",
  "AVX_NAMOR_PHOENIX_FIVE_225",
  "AVX_CYCLOPS_PHOENIX_FIVE_226",
  "AVX_EMMA_FROST_PHOENIX_FIVE_227",
  "AVX_COLOSSUS_PHOENIX_FIVE_228",
];
export const AVX_TRADE_BTN = "AVX_TRADE_243";
export const DEADPOOL_PATH_5_POINTS = "AVX_PATH_140";
export const DEADPOOL_PATH_10_POINTS = "AVX_PATH_141";
export const DEADPOOL_PATH_20_POINTS = "AVX_PATH_142";
export const DEADPOOL_FIGHT_BTN = "AVX_DEADPOOL_6969";
