import EQUIP_ANT_MAN_WRIST_GAUNTLETS from "../assets/rewards/equipment/EQUIP_ANT_MAN_WRIST_GAUNTLETS.jpg";
import EQUIP_ANT_MANS_SUIT from "../assets/rewards/equipment/EQUIP_ANT_MANS_SUIT.jpg";
import EQUIP_BETA_RAY_BILL_STORMBREAKER from "../assets/rewards/equipment/EQUIP_BETA_RAY_BILL_STORMBREAKER.jpg";
import EQUIP_BLACK_KNIGHT_EBONY_BLADE from "../assets/rewards/equipment/EQUIP_BLACK_KNIGHT_EBONY_BLADE.jpg";
import EQUIP_BLACK_PANTHER_HARD_LIGHT_SHIELD from "../assets/rewards/equipment/EQUIP_BLACK_PANTHER_HARD_LIGHT_SHIELD.jpg";
import EQUIP_BLACK_PANTHER_SHURI_HARD_LIGHT_SHIELD from "../assets/rewards/equipment/EQUIP_BLACK_PANTHER_SHURI_HARD_LIGHT_SHIELD.jpg";
import EQUIP_BLACK_PANTHER_SHURI_SPEAR_OF_BASHENGA from "../assets/rewards/equipment/EQUIP_BLACK_PANTHER_SHURI_SPEAR_OF_BASHENGA.jpg";
import EQUIP_BLACK_PANTHER_SPEAR_OF_BASHENGA from "../assets/rewards/equipment/EQUIP_BLACK_PANTHER_SPEAR_OF_BASHENGA.jpg";
import EQUIP_BLACK_WIDOW_WIDOWS_BITE from "../assets/rewards/equipment/EQUIP_BLACK_WIDOW_WIDOWS_BITE.jpg";
import EQUIP_BLADES_SWORD from "../assets/rewards/equipment/EQUIP_BLADES_SWORD.jpg";
import EQUIP_CAPTAIN_AMERICA_SAM_WILSON_CAPTAIN_AMERICAS_SHIELD from "../assets/rewards/equipment/EQUIP_CAPTAIN_AMERICA_SAM_WILSON_CAPTAIN_AMERICAS_SHIELD.jpg";
import EQUIP_CAPTAIN_AMERICAS_SHIELD from "../assets/rewards/equipment/EQUIP_CAPTAIN_AMERICAS_SHIELD.jpg";
import EQUIP_CAPTAIN_CARTERS_SHIELD from "../assets/rewards/equipment/EQUIP_CAPTAIN_CARTERS_SHIELD.jpg";
import EQUIP_COSMIC_GHOST_RIDER_HELL_CYCLE from "../assets/rewards/equipment/EQUIP_COSMIC_GHOST_RIDER_HELL_CYCLE.jpg";
import EQUIP_COSMIC_GHOST_RIDER_HELLFIRE_CHAIN from "../assets/rewards/equipment/EQUIP_COSMIC_GHOST_RIDER_HELLFIRE_CHAIN.jpg";
import EQUIP_CYBORG_SPIDER_MAN_SONIC_CANNON from "../assets/rewards/equipment/EQUIP_CYBORG_SPIDER_MAN_SONIC_CANNON.jpg";
import EQUIP_CYCLOPS_VISOR from "../assets/rewards/equipment/EQUIP_CYCLOPS_VISOR.jpg";
import EQUIP_DAREDEVIL_BILLY_CLUB from "../assets/rewards/equipment/EQUIP_DAREDEVIL_BILLY_CLUB.jpg";
import EQUIP_DARKCHILD_SOULSWORD from "../assets/rewards/equipment/EQUIP_DARKCHILD_SOULSWORD.jpg";
import EQUIP_ELEKTRA_SAI from "../assets/rewards/equipment/EQUIP_ELEKTRA_SAI.jpg";
import EQUIP_ELSA_BLOODSTONE_MORDREDS_CAUSEWAY from "../assets/rewards/equipment/EQUIP_ELSA_BLOODSTONE_MORDREDS_CAUSEWAY.jpg";
import EQUIP_GAMBIT_DECK_OF_CARDS from "../assets/rewards/equipment/EQUIP_GAMBIT_DECK_OF_CARDS.jpg";
import EQUIP_GAMORA_GODSLAYER from "../assets/rewards/equipment/EQUIP_GAMORA_GODSLAYER.jpg";
import EQUIP_GENERIC_AIRLIFT from "../assets/rewards/equipment/EQUIP_GENERIC_AIRLIFT.jpg";
import EQUIP_GENERIC_BODY_ARMOR from "../assets/rewards/equipment/EQUIP_GENERIC_BODY_ARMOR.jpg";
import EQUIP_GENERIC_COMMUNICATION_DEVICE from "../assets/rewards/equipment/EQUIP_GENERIC_COMMUNICATION_DEVICE.jpg";
import EQUIP_GENERIC_MAKESHIFT_WEAPON from "../assets/rewards/equipment/EQUIP_GENERIC_MAKESHIFT_WEAPON.jpg";
import EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELL_CYCLE from "../assets/rewards/equipment/EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELL_CYCLE.jpg";
import EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELLFIRE_CHAIN from "../assets/rewards/equipment/EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELLFIRE_CHAIN.jpg";
import EQUIP_GHOST_SPIDER_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_GHOST_SPIDER_WEB_SHOOTERS.jpg";
import EQUIP_TRICK_ARROW_EXPLOSIVE from "../assets/rewards/equipment/EQUIP_TRICK_ARROW_EXPLOSIVE.jpg";
import EQUIP_TRICK_ARROW_PYM_PARTICLES from "../assets/rewards/equipment/EQUIP_TRICK_ARROW_PYM_PARTICLES.jpg";
import EQUIP_TRICK_ARROW_SMOKE_BOMB from "../assets/rewards/equipment/EQUIP_TRICK_ARROW_SMOKE_BOMB.jpg";
import EQUIP_TRICK_ARROW_WIRE from "../assets/rewards/equipment/EQUIP_TRICK_ARROW_WIRE.jpg";
import EQUIP_HULKBUSTER_IRON_MAN_DEFLECTOR_SHIELDS from "../assets/rewards/equipment/EQUIP_HULKBUSTER_IRON_MAN_DEFLECTOR_SHIELDS.jpg";
import EQUIP_HULKBUSTER_IRON_MAN_OMNIBEAM from "../assets/rewards/equipment/EQUIP_HULKBUSTER_IRON_MAN_OMNIBEAM.jpg";
import EQUIP_HULKLING_EXCELSIOR from "../assets/rewards/equipment/EQUIP_HULKLING_EXCELSIOR.jpg";
import EQUIP_NEGA_WEDDING_RING from "../assets/rewards/equipment/EQUIP_NEGA_WEDDING_RING.jpg";
import EQUIP_IRON_LAD_NEUROKINETIK_ARMOR from "../assets/rewards/equipment/EQUIP_IRON_LAD_NEUROKINETIK_ARMOR.jpg";
import EQUIP_IRON_MAN_DEFLECTOR_SHIELDS from "../assets/rewards/equipment/EQUIP_IRON_MAN_DEFLECTOR_SHIELDS.jpg";
import EQUIP_IRON_MAN_OMNIBEAM from "../assets/rewards/equipment/EQUIP_IRON_MAN_OMNIBEAM.jpg";
import EQUIP_IRON_MAN_STEALTH_FIELD_GENERATOR from "../assets/rewards/equipment/EQUIP_IRON_MAN_STEALTH_FIELD_GENERATOR.jpg";
import EQUIP_IRON_SPIDER_WALDOES from "../assets/rewards/equipment/EQUIP_IRON_SPIDER_WALDOES.jpg";
import EQUIP_IRON_SPIDER_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_IRON_SPIDER_WEB_SHOOTERS.jpg";
import EQUIP_LOKI_SCEPTER from "../assets/rewards/equipment/EQUIP_LOKI_SCEPTER.jpg";
import EQUIP_MAGIK_SOULSWORD from "../assets/rewards/equipment/EQUIP_MAGIK_SOULSWORD.jpg";
import EQUIP_MAGNETO_AOA_MAGNETOS_HELMET from "../assets/rewards/equipment/EQUIP_MAGNETO_AOA_MAGNETOS_HELMET.jpg";
import EQUIP_MAGNETOS_HELMET from "../assets/rewards/equipment/EQUIP_MAGNETOS_HELMET.jpg";
import EQUIP_MIGHTY_THOR_MJOLNIR from "../assets/rewards/equipment/EQUIP_MIGHTY_THOR_MJOLNIR.jpg";
import EQUIP_MILES_MORALES_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_MILES_MORALES_WEB_SHOOTERS.jpg";
import EQUIP_MOON_KNIGHT_CRESCENT_DARTS from "../assets/rewards/equipment/EQUIP_MOON_KNIGHT_CRESCENT_DARTS.jpg";
import EQUIP_MOON_KNIGHTS_SUIT from "../assets/rewards/equipment/EQUIP_MOON_KNIGHTS_SUIT.jpg";
import EQUIP_NAMOR_TRIDENT from "../assets/rewards/equipment/EQUIP_NAMOR_TRIDENT.jpg";
import EQUIP_NICK_FURY_BATTLE_SUIT from "../assets/rewards/equipment/EQUIP_NICK_FURY_BATTLE_SUIT.jpg";
import EQUIP_OKOYE_VIBRANIUM_SPEAR from "../assets/rewards/equipment/EQUIP_OKOYE_VIBRANIUM_SPEAR.jpg";
import EQUIP_PATRIOTS_SHIELD from "../assets/rewards/equipment/EQUIP_PATRIOTS_SHIELD.jpg";
import EQUIP_PENI_PARKER_BATTERIES from "../assets/rewards/equipment/EQUIP_PENI_PARKER_BATTERIES.jpg";
import EQUIP_SCARLET_SPIDER_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_SCARLET_SPIDER_WEB_SHOOTERS.jpg";
import EQUIP_SCARLET_WITCH_DARKHOLD from "../assets/rewards/equipment/EQUIP_SCARLET_WITCH_DARKHOLD.jpg";
import EQUIP_SHANG_CHI_NUNCHAKU from "../assets/rewards/equipment/EQUIP_SHANG_CHI_NUNCHAKU.jpg";
import EQUIP_SPIDER_HAM_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_SPIDER_HAM_WEB_SHOOTERS.jpg";
import EQUIP_SPIDER_MAN_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_SPIDER_MAN_WEB_SHOOTERS.jpg";
import EQUIP_SPIDER_PUNK_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_SPIDER_PUNK_WEB_SHOOTERS.jpg";
import EQUIP_STARLORD_SPACE_HELMET from "../assets/rewards/equipment/EQUIP_STARLORD_SPACE_HELMET.jpg";
import EQUIP_STARLORD_TRANSLATOR_IMPLANT from "../assets/rewards/equipment/EQUIP_STARLORD_TRANSLATOR_IMPLANT.jpg";
import EQUIP_STATURES_SUIT from "../assets/rewards/equipment/EQUIP_STATURES_SUIT.jpg";
import EQUIP_SUPERIOR_SPIDER_MAN_MECHANICAL_SPIDER_ARMS from "../assets/rewards/equipment/EQUIP_SUPERIOR_SPIDER_MAN_MECHANICAL_SPIDER_ARMS.jpg";
import EQUIP_SUPERIOR_SPIDER_MAN_WEB_SHOOTERS from "../assets/rewards/equipment/EQUIP_SUPERIOR_SPIDER_MAN_WEB_SHOOTERS.jpg";
import EQUIP_THOR_MJOLNIR from "../assets/rewards/equipment/EQUIP_THOR_MJOLNIR.jpg";
import EQUIP_US_AGENTS_SHIELD from "../assets/rewards/equipment/EQUIP_US_AGENTS_SHIELD.jpg";
import EQUIP_VISION_SOLAR_GEM from "../assets/rewards/equipment/EQUIP_VISION_SOLAR_GEM.jpg";
import EQUIP_WAR_MACHINE_DEFLECTOR_SHIELDS from "../assets/rewards/equipment/EQUIP_WAR_MACHINE_DEFLECTOR_SHIELDS.jpg";
import EQUIP_WAR_MACHINE_OMNIBEAM from "../assets/rewards/equipment/EQUIP_WAR_MACHINE_OMNIBEAM.jpg";
import EQUIP_WAR_MACHINE_STEALTH_FIELD_GENERATOR from "../assets/rewards/equipment/EQUIP_WAR_MACHINE_STEALTH_FIELD_GENERATOR.jpg";
import EQUIP_WASPS_STING from "../assets/rewards/equipment/EQUIP_WASPS_STING.jpg";
import EQUIP_WASPS_SUIT from "../assets/rewards/equipment/EQUIP_WASPS_SUIT.jpg";
import EQUIP_WHITE_WIDOW_BATTLE_BATONS from "../assets/rewards/equipment/EQUIP_WHITE_WIDOW_BATTLE_BATONS.jpg";
import EQUIP_WHITE_WIDOW_WIDOWS_BITE from "../assets/rewards/equipment/EQUIP_WHITE_WIDOW_WIDOWS_BITE.jpg";
import EQUIP_YELLOWJACKET_DISRUPTOR_STINGS from "../assets/rewards/equipment/EQUIP_YELLOWJACKET_DISRUPTOR_STINGS.jpg";
import { EquipKey } from "../types/equipment";

export const equipmentIconSrcs: { [key in EquipKey]?: string } = {
  EQUIP_ANT_MAN_WRIST_GAUNTLETS: EQUIP_ANT_MAN_WRIST_GAUNTLETS,
  EQUIP_ANT_MANS_SUIT: EQUIP_ANT_MANS_SUIT,
  EQUIP_BETA_RAY_BILL_STORMBREAKER: EQUIP_BETA_RAY_BILL_STORMBREAKER,
  EQUIP_BLACK_KNIGHT_EBONY_BLADE: EQUIP_BLACK_KNIGHT_EBONY_BLADE,
  EQUIP_BLACK_PANTHER_HARD_LIGHT_SHIELD: EQUIP_BLACK_PANTHER_HARD_LIGHT_SHIELD,
  EQUIP_BLACK_PANTHER_SHURI_HARD_LIGHT_SHIELD: EQUIP_BLACK_PANTHER_SHURI_HARD_LIGHT_SHIELD,
  EQUIP_BLACK_PANTHER_SHURI_SPEAR_OF_BASHENGA: EQUIP_BLACK_PANTHER_SHURI_SPEAR_OF_BASHENGA,
  EQUIP_BLACK_PANTHER_SPEAR_OF_BASHENGA: EQUIP_BLACK_PANTHER_SPEAR_OF_BASHENGA,
  // EQUIP_BLACK_WIDOW_BATTLE_BATONS: EQUIP_BLACK_WIDOW_BATTLE_BATONS,
  EQUIP_BLACK_WIDOW_WIDOWS_BITE: EQUIP_BLACK_WIDOW_WIDOWS_BITE,
  EQUIP_BLADES_SWORD: EQUIP_BLADES_SWORD,
  // EQUIP_CAPTAIN_AMERICA_CLASSIC_CAPTAIN_AMERICAS_SHIELD: EQUIP_CAPTAIN_AMERICA_CLASSIC_CAPTAIN_AMERICAS_SHIELD,
  EQUIP_CAPTAIN_AMERICA_SAM_WILSON_CAPTAIN_AMERICAS_SHIELD: EQUIP_CAPTAIN_AMERICA_SAM_WILSON_CAPTAIN_AMERICAS_SHIELD,
  EQUIP_CAPTAIN_AMERICAS_SHIELD: EQUIP_CAPTAIN_AMERICAS_SHIELD,
  // EQUIP_CAPTAIN_BRITAIN_BETSY_BRADDOCK_STARLIGHT_SWORD: EQUIP_CAPTAIN_BRITAIN_BETSY_BRADDOCK_STARLIGHT_SWORD,
  EQUIP_CAPTAIN_CARTERS_SHIELD: EQUIP_CAPTAIN_CARTERS_SHIELD,
  EQUIP_COSMIC_GHOST_RIDER_HELL_CYCLE: EQUIP_COSMIC_GHOST_RIDER_HELL_CYCLE,
  EQUIP_COSMIC_GHOST_RIDER_HELLFIRE_CHAIN: EQUIP_COSMIC_GHOST_RIDER_HELLFIRE_CHAIN,
  EQUIP_CYBORG_SPIDER_MAN_SONIC_CANNON: EQUIP_CYBORG_SPIDER_MAN_SONIC_CANNON,
  // EQUIP_CYCLOPS_FIRST_CLASS_CYCLOPS_VISOR: EQUIP_CYCLOPS_FIRST_CLASS_CYCLOPS_VISOR,
  EQUIP_CYCLOPS_VISOR: EQUIP_CYCLOPS_VISOR,
  EQUIP_DAREDEVIL_BILLY_CLUB: EQUIP_DAREDEVIL_BILLY_CLUB,
  EQUIP_DARKCHILD_SOULSWORD: EQUIP_DARKCHILD_SOULSWORD,
  EQUIP_ELEKTRA_SAI: EQUIP_ELEKTRA_SAI,
  EQUIP_ELSA_BLOODSTONE_MORDREDS_CAUSEWAY: EQUIP_ELSA_BLOODSTONE_MORDREDS_CAUSEWAY,
  EQUIP_GAMBIT_DECK_OF_CARDS: EQUIP_GAMBIT_DECK_OF_CARDS,
  EQUIP_GAMORA_GODSLAYER: EQUIP_GAMORA_GODSLAYER,
  EQUIP_GENERIC_AIRLIFT: EQUIP_GENERIC_AIRLIFT,
  EQUIP_GENERIC_BODY_ARMOR: EQUIP_GENERIC_BODY_ARMOR,
  EQUIP_GENERIC_COMMUNICATION_DEVICE: EQUIP_GENERIC_COMMUNICATION_DEVICE,
  EQUIP_GENERIC_MAKESHIFT_WEAPON: EQUIP_GENERIC_MAKESHIFT_WEAPON,
  // EQUIP_GHOST_RIDER_HELL_CHARGER: EQUIP_GHOST_RIDER_HELL_CHARGER,
  // EQUIP_GHOST_RIDER_HELLFIRE_CHAIN: EQUIP_GHOST_RIDER_HELLFIRE_CHAIN,
  EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELL_CYCLE: EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELL_CYCLE,
  EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELLFIRE_CHAIN: EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELLFIRE_CHAIN,
  EQUIP_GHOST_SPIDER_WEB_SHOOTERS: EQUIP_GHOST_SPIDER_WEB_SHOOTERS,
  EQUIP_HAWKEYE_TRICK_ARROW_EXPLOSIVE: EQUIP_TRICK_ARROW_EXPLOSIVE,
  EQUIP_HAWKEYE_TRICK_ARROW_PYM_PARTICLES: EQUIP_TRICK_ARROW_PYM_PARTICLES,
  EQUIP_HAWKEYE_TRICK_ARROW_SMOKE_BOMB: EQUIP_TRICK_ARROW_SMOKE_BOMB,
  EQUIP_HAWKEYE_TRICK_ARROW_WIRE: EQUIP_TRICK_ARROW_WIRE,
  EQUIP_HULKBUSTER_IRON_MAN_DEFLECTOR_SHIELDS: EQUIP_HULKBUSTER_IRON_MAN_DEFLECTOR_SHIELDS,
  EQUIP_HULKBUSTER_IRON_MAN_OMNIBEAM: EQUIP_HULKBUSTER_IRON_MAN_OMNIBEAM,
  EQUIP_HULKLING_EXCELSIOR: EQUIP_HULKLING_EXCELSIOR,
  EQUIP_HULKLING_NEGA_WEDDING_RING: EQUIP_NEGA_WEDDING_RING,
  EQUIP_IRON_LAD_NEUROKINETIK_ARMOR: EQUIP_IRON_LAD_NEUROKINETIK_ARMOR,
  // EQUIP_IRON_MAN_CIVIL_WAR_DEFLECTOR_SHIELDS: EQUIP_IRON_MAN_CIVIL_WAR_DEFLECTOR_SHIELDS,
  // EQUIP_IRON_MAN_CIVIL_WAR_OMNIBEAM: EQUIP_IRON_MAN_CIVIL_WAR_OMNIBEAM,
  // EQUIP_IRON_MAN_CIVIL_WAR_STEALTH_FIELD_GENERATOR: EQUIP_IRON_MAN_CIVIL_WAR_STEALTH_FIELD_GENERATOR,
  EQUIP_IRON_MAN_DEFLECTOR_SHIELDS: EQUIP_IRON_MAN_DEFLECTOR_SHIELDS,
  EQUIP_IRON_MAN_OMNIBEAM: EQUIP_IRON_MAN_OMNIBEAM,
  EQUIP_IRON_MAN_STEALTH_FIELD_GENERATOR: EQUIP_IRON_MAN_STEALTH_FIELD_GENERATOR,
  EQUIP_IRON_SPIDER_WALDOES: EQUIP_IRON_SPIDER_WALDOES,
  EQUIP_IRON_SPIDER_WEB_SHOOTERS: EQUIP_IRON_SPIDER_WEB_SHOOTERS,
  EQUIP_KATE_BISHOP_TRICK_ARROW_EXPLOSIVE: EQUIP_TRICK_ARROW_EXPLOSIVE,
  EQUIP_KATE_BISHOP_TRICK_ARROW_PYM_PARTICLES: EQUIP_TRICK_ARROW_PYM_PARTICLES,
  EQUIP_KATE_BISHOP_TRICK_ARROW_SMOKE_BOMB: EQUIP_TRICK_ARROW_SMOKE_BOMB,
  EQUIP_KATE_BISHOP_TRICK_ARROW_WIRE: EQUIP_TRICK_ARROW_WIRE,
  EQUIP_LOKI_SCEPTER: EQUIP_LOKI_SCEPTER,
  EQUIP_MAGIK_SOULSWORD: EQUIP_MAGIK_SOULSWORD,
  EQUIP_MAGNETO_AOA_MAGNETOS_HELMET: EQUIP_MAGNETO_AOA_MAGNETOS_HELMET,
  EQUIP_MAGNETOS_HELMET: EQUIP_MAGNETOS_HELMET,
  EQUIP_MIGHTY_THOR_MJOLNIR: EQUIP_MIGHTY_THOR_MJOLNIR,
  EQUIP_MILES_MORALES_WEB_SHOOTERS: EQUIP_MILES_MORALES_WEB_SHOOTERS,
  // EQUIP_MOCKINGBIRD_BATTLE_STAVES: EQUIP_MOCKINGBIRD_BATTLE_STAVES,
  EQUIP_MOON_KNIGHT_CRESCENT_DARTS: EQUIP_MOON_KNIGHT_CRESCENT_DARTS,
  EQUIP_MOON_KNIGHTS_SUIT: EQUIP_MOON_KNIGHTS_SUIT,
  EQUIP_NAMOR_TRIDENT: EQUIP_NAMOR_TRIDENT,
  EQUIP_NICK_FURY_BATTLE_SUIT: EQUIP_NICK_FURY_BATTLE_SUIT,
  EQUIP_OKOYE_VIBRANIUM_SPEAR: EQUIP_OKOYE_VIBRANIUM_SPEAR,
  EQUIP_PATRIOTS_SHIELD: EQUIP_PATRIOTS_SHIELD,
  EQUIP_PENI_PARKER_BATTERIES: EQUIP_PENI_PARKER_BATTERIES,
  // EQUIP_RONINS_BLADE: EQUIP_RONINS_BLADE,
  EQUIP_SCARLET_SPIDER_WEB_SHOOTERS: EQUIP_SCARLET_SPIDER_WEB_SHOOTERS,
  EQUIP_SCARLET_WITCH_DARKHOLD: EQUIP_SCARLET_WITCH_DARKHOLD,
  EQUIP_SHANG_CHI_NUNCHAKU: EQUIP_SHANG_CHI_NUNCHAKU,
  EQUIP_SPIDER_HAM_WEB_SHOOTERS: EQUIP_SPIDER_HAM_WEB_SHOOTERS,
  EQUIP_SPIDER_MAN_WEB_SHOOTERS: EQUIP_SPIDER_MAN_WEB_SHOOTERS,
  EQUIP_SPIDER_PUNK_WEB_SHOOTERS: EQUIP_SPIDER_PUNK_WEB_SHOOTERS,
  EQUIP_STARLORD_SPACE_HELMET: EQUIP_STARLORD_SPACE_HELMET,
  EQUIP_STARLORD_TRANSLATOR_IMPLANT: EQUIP_STARLORD_TRANSLATOR_IMPLANT,
  EQUIP_STATURES_SUIT: EQUIP_STATURES_SUIT,
  EQUIP_SUPERIOR_SPIDER_MAN_MECHANICAL_SPIDER_ARMS: EQUIP_SUPERIOR_SPIDER_MAN_MECHANICAL_SPIDER_ARMS,
  EQUIP_SUPERIOR_SPIDER_MAN_WEB_SHOOTERS: EQUIP_SUPERIOR_SPIDER_MAN_WEB_SHOOTERS,
  EQUIP_THOR_MJOLNIR: EQUIP_THOR_MJOLNIR,
  EQUIP_US_AGENTS_SHIELD: EQUIP_US_AGENTS_SHIELD,
  EQUIP_VISION_SOLAR_GEM: EQUIP_VISION_SOLAR_GEM,
  EQUIP_WAR_MACHINE_DEFLECTOR_SHIELDS: EQUIP_WAR_MACHINE_DEFLECTOR_SHIELDS,
  EQUIP_WAR_MACHINE_OMNIBEAM: EQUIP_WAR_MACHINE_OMNIBEAM,
  EQUIP_WAR_MACHINE_STEALTH_FIELD_GENERATOR: EQUIP_WAR_MACHINE_STEALTH_FIELD_GENERATOR,
  EQUIP_WASPS_STING: EQUIP_WASPS_STING,
  EQUIP_WASPS_SUIT: EQUIP_WASPS_SUIT,
  EQUIP_WHITE_WIDOW_BATTLE_BATONS: EQUIP_WHITE_WIDOW_BATTLE_BATONS,
  EQUIP_WHITE_WIDOW_WIDOWS_BITE: EQUIP_WHITE_WIDOW_WIDOWS_BITE,
  EQUIP_WICCAN_NEGA_WEDDING_RING: EQUIP_NEGA_WEDDING_RING,
  EQUIP_YELLOWJACKET_DISRUPTOR_STINGS: EQUIP_YELLOWJACKET_DISRUPTOR_STINGS
}
