const EQUIP_LIST = [
  "EQUIP_ANT_MAN_WRIST_GAUNTLETS",
  "EQUIP_ANT_MANS_SUIT",
  "EQUIP_BETA_RAY_BILL_STORMBREAKER",
  "EQUIP_BLACK_KNIGHT_EBONY_BLADE",
  "EQUIP_BLACK_PANTHER_HARD_LIGHT_SHIELD",
  "EQUIP_BLACK_PANTHER_SHURI_HARD_LIGHT_SHIELD",
  "EQUIP_BLACK_PANTHER_SHURI_SPEAR_OF_BASHENGA",
  "EQUIP_BLACK_PANTHER_SPEAR_OF_BASHENGA",
  "EQUIP_BLACK_WIDOW_BATTLE_BATONS",
  "EQUIP_BLACK_WIDOW_WIDOWS_BITE",
  "EQUIP_BLADES_SWORD",
  "EQUIP_CAPTAIN_AMERICA_CLASSIC_CAPTAIN_AMERICAS_SHIELD",
  "EQUIP_CAPTAIN_AMERICA_SAM_WILSON_CAPTAIN_AMERICAS_SHIELD",
  "EQUIP_CAPTAIN_AMERICAS_SHIELD",
  "EQUIP_CAPTAIN_BRITAIN_BETSY_BRADDOCK_STARLIGHT_SWORD",
  "EQUIP_CAPTAIN_CARTERS_SHIELD",
  "EQUIP_COSMIC_GHOST_RIDER_HELL_CYCLE",
  "EQUIP_COSMIC_GHOST_RIDER_HELLFIRE_CHAIN",
  "EQUIP_CYBORG_SPIDER_MAN_SONIC_CANNON",
  "EQUIP_CYCLOPS_FIRST_CLASS_CYCLOPS_VISOR",
  "EQUIP_CYCLOPS_VISOR",
  "EQUIP_DAREDEVIL_BILLY_CLUB",
  "EQUIP_DARKCHILD_SOULSWORD",
  "EQUIP_ELEKTRA_SAI",
  "EQUIP_ELSA_BLOODSTONE_MORDREDS_CAUSEWAY",
  "EQUIP_GAMBIT_DECK_OF_CARDS",
  "EQUIP_GAMORA_GODSLAYER",
  "EQUIP_GENERIC_AIRLIFT",
  "EQUIP_GENERIC_BODY_ARMOR",
  "EQUIP_GENERIC_COMMUNICATION_DEVICE",
  "EQUIP_GENERIC_MAKESHIFT_WEAPON",
  "EQUIP_GHOST_RIDER_HELL_CHARGER",
  "EQUIP_GHOST_RIDER_HELLFIRE_CHAIN",
  "EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELL_CYCLE",
  "EQUIP_GHOST_RIDER_JOHNNY_BLAZE_HELLFIRE_CHAIN",
  "EQUIP_GHOST_SPIDER_WEB_SHOOTERS",
  "EQUIP_GHOST_SPIDER_WEB_SHOOTERS",
  "EQUIP_HAWKEYE_TRICK_ARROW_EXPLOSIVE",
  "EQUIP_HAWKEYE_TRICK_ARROW_PYM_PARTICLES",
  "EQUIP_HAWKEYE_TRICK_ARROW_SMOKE_BOMB",
  "EQUIP_HAWKEYE_TRICK_ARROW_WIRE",
  "EQUIP_HULKBUSTER_IRON_MAN_DEFLECTOR_SHIELDS",
  "EQUIP_HULKBUSTER_IRON_MAN_OMNIBEAM",
  "EQUIP_HULKLING_EXCELSIOR",
  "EQUIP_HULKLING_NEGA_WEDDING_RING",
  "EQUIP_IRON_LAD_NEUROKINETIK_ARMOR",
  "EQUIP_IRON_MAN_CIVIL_WAR_DEFLECTOR_SHIELDS",
  "EQUIP_IRON_MAN_CIVIL_WAR_OMNIBEAM",
  "EQUIP_IRON_MAN_CIVIL_WAR_STEALTH_FIELD_GENERATOR",
  "EQUIP_IRON_MAN_DEFLECTOR_SHIELDS",
  "EQUIP_IRON_MAN_OMNIBEAM",
  "EQUIP_IRON_MAN_STEALTH_FIELD_GENERATOR",
  "EQUIP_IRON_SPIDER_WALDOES",
  "EQUIP_IRON_SPIDER_WEB_SHOOTERS",
  "EQUIP_KATE_BISHOP_TRICK_ARROW_EXPLOSIVE",
  "EQUIP_KATE_BISHOP_TRICK_ARROW_PYM_PARTICLES",
  "EQUIP_KATE_BISHOP_TRICK_ARROW_SMOKE_BOMB",
  "EQUIP_KATE_BISHOP_TRICK_ARROW_WIRE",
  "EQUIP_LOKI_SCEPTER",
  "EQUIP_MAGIK_SOULSWORD",
  "EQUIP_MAGNETO_AOA_MAGNETOS_HELMET",
  "EQUIP_MAGNETOS_HELMET",
  "EQUIP_MIGHTY_THOR_MJOLNIR",
  "EQUIP_MILES_MORALES_WEB_SHOOTERS",
  "EQUIP_MOCKINGBIRD_BATTLE_STAVES",
  "EQUIP_MOON_KNIGHT_CRESCENT_DARTS",
  "EQUIP_MOON_KNIGHTS_SUIT",
  "EQUIP_NAMOR_TRIDENT",
  "EQUIP_NICK_FURY_BATTLE_SUIT",
  "EQUIP_OKOYE_VIBRANIUM_SPEAR",
  "EQUIP_PATRIOTS_SHIELD",
  "EQUIP_PENI_PARKER_BATTERIES",
  "EQUIP_RONINS_BLADE",
  "EQUIP_SCARLET_SPIDER_WEB_SHOOTERS",
  "EQUIP_SCARLET_WITCH_DARKHOLD",
  "EQUIP_SHANG_CHI_NUNCHAKU",
  "EQUIP_SPIDER_HAM_WEB_SHOOTERS",
  "EQUIP_SPIDER_MAN_WEB_SHOOTERS",
  "EQUIP_SPIDER_PUNK_WEB_SHOOTERS",
  "EQUIP_STARLORD_SPACE_HELMET",
  "EQUIP_STARLORD_TRANSLATOR_IMPLANT",
  "EQUIP_STATURES_SUIT",
  "EQUIP_SUPERIOR_SPIDER_MAN_MECHANICAL_SPIDER_ARMS",
  "EQUIP_SUPERIOR_SPIDER_MAN_WEB_SHOOTERS",
  "EQUIP_THOR_MJOLNIR",
  "EQUIP_US_AGENTS_SHIELD",
  "EQUIP_VISION_SOLAR_GEM",
  "EQUIP_WAR_MACHINE_DEFLECTOR_SHIELDS",
  "EQUIP_WAR_MACHINE_OMNIBEAM",
  "EQUIP_WAR_MACHINE_STEALTH_FIELD_GENERATOR",
  "EQUIP_WASPS_STING",
  "EQUIP_WASPS_SUIT",
  "EQUIP_WHITE_WIDOW_BATTLE_BATONS",
  "EQUIP_WHITE_WIDOW_WIDOWS_BITE",
  "EQUIP_WICCAN_NEGA_WEDDING_RING",
  "EQUIP_YELLOWJACKET_DISRUPTOR_STINGS",
] as const;

export type EquipKey = (typeof EQUIP_LIST)[number];

export type EquipName =
  | "Airlift"
  | "Ant-Man's Suit"
  | "Batteries"
  | "Battle Batons"
  | "Battle Staves"
  | "Battle Suit"
  | "Billy Club"
  | "Blade's Sword"
  | "Body Armor"
  | "Captain America's Shield"
  | "Captain Carter's Shield"
  | "Communication Device"
  | "Crescent Darts"
  | "Cyclops' Visor"
  | "Darkhold"
  | "Deck of Cards"
  | "Deflector Shields"
  | "Disruptor Stings"
  | "Ebony Blade"
  | "Excelsior"
  | "Godslayer"
  | "Hard Light Shield"
  | "Hell Charger"
  | "Hell Cycle"
  | "Hellfire Chain"
  | "Magneto's Helmet"
  | "Makeshift Weapon"
  | "Mechanical Spider-Arms"
  | "Mjolnir"
  | "Moon Knight Suit"
  | "Mordred's Causeway"
  | "Nega Wedding Ring"
  | "Neurokinetik Armor"
  | "Nunchaku"
  | "Omnibeam"
  | "Patriot's Shield"
  | "Ronin's Blade"
  | "Sai"
  | "Scepter"
  | "Solar Gem"
  | "Sonic Cannon"
  | "Soulsword"
  | "Space Helmet"
  | "Spear of Bashenga"
  | "Starlight Sword"
  | "Stature's Suit"
  | "Stealth Field Generator"
  | "Stormbreaker"
  | "Translator Implant"
  | "Trick Arrow-Explosive"
  | "Trick Arrow-Pym Particles"
  | "Trick Arrow-Smoke Bomb"
  | "Trick Arrow-Wire"
  | "Trident"
  | "U.S. Agent's Shield"
  | "Vibranium Spear"
  | "Waldoes"
  | "Wasp's Sting"
  | "Wasp's Suit"
  | "Web-Shooters"
  | "Widow's Bite"
  | "Wrist Gauntlets";

export const isEquipKey = (s: string): s is EquipKey =>
  EQUIP_LIST.includes(s as EquipKey);
